In [1]:
import yfinance as yf
import pandas as pd

# data = yf.download("COMI.CA", start="2025-01-01", end="2026-03-10")
# data.to_csv("cib_stock_data.csv")

In [14]:
data = yf.download("EHDR.CA", start="2025-01-01", end="2026-03-11")

data

[*********************100%***********************]  1 of 1 completed

Price          Close      High       Low      Open    Volume
Ticker       EHDR.CA   EHDR.CA   EHDR.CA   EHDR.CA   EHDR.CA
Date
2025-01-02  0.280524  0.282000  0.279047  0.276832   9610182
2025-01-05  0.281262  0.287906  0.280524  0.280524  18342398
2025-01-06  0.279785  0.284215  0.276832  0.281262  15706352
2025-01-08  0.275356  0.281262  0.275356  0.279785  10617895
2025-01-09  0.276832  0.280524  0.276832  0.275356   6051993
...              ...       ...       ...       ...       ...
2026-03-03  1.980000  2.030000  1.960000  2.000000   3271378
2026-03-04  2.010000  2.020000  1.970000  1.980000   2794792
2026-03-05  2.040000  2.070000  2.010000  2.010000   4357202
2026-03-08  2.050000  2.070000  2.040000  2.040000   1940689
2026-03-09  2.050000  2.070000  2.040000  2.050000   1840390

[287 rows x 5 columns]

In [25]:
from tvDatafeed import TvDatafeed, Interval
import time

In [ ]:
# Initialize (no login needed for basic EGX data)
# tv = TvDatafeed()

# # Define your stock and exchange
# symbol = "EHDR"
# exchange = "EGX"

# # n_bars=250 gives you approx. 1 year of trading days (excluding weekends/holidays)
# data = tv.get_hist(symbol=symbol, exchange=exchange, interval=Interval.in_daily, n_bars=250)

# if data is not None:
#     print(f"--- Historical Data for {symbol} ---")
#     print(data.head()) # Oldest data (1 year ago)
#     print(data.tail()) # Newest data (Today's price)
    
#     # Save it to Excel/CSV
#     data.to_csv(f"{symbol}_one_year.csv")
#     print(f"💾 Saved to {symbol}_one_year.csv")
# else:
#     print("❌ Data not found. Check if the symbol/exchange is correct.")

--- Historical Data for RAYA ---
                       symbol  open  high   low  close      volume
datetime
2025-02-26 10:00:00  EGX:RAYA  2.50  2.54  2.47   2.48  13655777.0
2025-02-27 10:00:00  EGX:RAYA  2.48  2.50  2.43   2.43   9639133.0
2025-03-02 10:00:00  EGX:RAYA  2.43  2.46  2.41   2.43   4508509.0
2025-03-03 10:00:00  EGX:RAYA  2.43  2.46  2.42   2.44   5273187.0
2025-03-04 10:00:00  EGX:RAYA  2.44  2.45  2.42   2.43   3682413.0
                       symbol  open  high   low  close      volume
datetime
2026-03-04 10:00:00  EGX:RAYA  5.38  5.52  5.20   5.43  13541891.0
2026-03-05 10:00:00  EGX:RAYA  5.43  5.57  5.31   5.34   9646992.0
2026-03-08 10:00:00  EGX:RAYA  5.34  5.55  5.26   5.37  12408694.0
2026-03-09 10:00:00  EGX:RAYA  5.37  5.55  5.37   5.49  13679883.0
2026-03-10 10:00:00  EGX:RAYA  5.49  6.02  5.49   5.83  36706928.0
💾 Saved to RAYA_one_year.csv

In [42]:
tv = TvDatafeed()

# Define your stock and exchange
symbol = "COMI"
exchange = "EGX"

# n_bars=250 gives you approx. 1 year of trading days (excluding weekends/holidays)
data = tv.get_hist(symbol=symbol, exchange=exchange, interval=Interval.in_daily, n_bars=250)

data

,symbol,open,high,low,close,volume
datetime,,,,,,
2025-02-26 10:00:00,EGX:COMI,70.545384,71.054474,69.554476,69.554476,3.003486e+06
2025-02-27 10:00:00,EGX:COMI,69.554476,70.172657,68.818113,68.818113,5.766143e+06
2025-03-02 10:00:00,EGX:COMI,68.818113,69.627203,68.818113,69.545385,1.152848e+06
2025-03-03 10:00:00,EGX:COMI,69.545385,70.636293,69.454476,70.099930,3.546113e+06
2025-03-04 10:00:00,EGX:COMI,70.099930,70.499929,69.318112,69.318112,1.472292e+06
...,...,...,...,...,...,...
2026-03-04 10:00:00,EGX:COMI,123.900000,124.000000,111.000000,121.500000,6.593274e+06
2026-03-05 10:00:00,EGX:COMI,121.500000,127.020000,121.500000,126.000000,6.551172e+06
2026-03-08 10:00:00,EGX:COMI,126.000000,126.000000,121.500000,121.910000,2.128512e+06
2026-03-09 10:00:00,EGX:COMI,121.910000,123.200000,118.040000,123.000000,3.503813e+06
2026-03-10 10:00:00,EGX:COMI,123.000000,129.500000,123.000000,129.500000,3.239515e+06